cagov/cannabis.ca.gov

src/manual-caweb.v1.0.1.js
Including an external JS bundle that's in active development and a temporary image replacement until local file saving is implemented
=> Update manual CSS with some patches used on production - 

src/manual-caweb.v1.0.1.js
Add footer link to our manual JS.
=> Add link to homepage to manual js

.github/workflows/eleventy_build.yml, src/components/branding/branding.html, src/components/menu/_style.scss, src/components/menu/index.js, src/components/utility-header/_style.scss, src/css/sass/_links.scss, src/templates/_includes/footer.njk, src/templates/_includes/nav-component.njk
This PR contains:
- addition of dropdown menu box shadows per Adam's designs. Adam reviewed this and approved
- Some minor css fixes to mobile menu alignment 
- Minor accessibility tweaks to fix audit flags, top level menu element should not start out aria-hidden
=> Menu styles

package-lock.json, package.json
Packages bumped with fixes from https://github.com/cagov/design-system/pull/51
=> bumped packages with recent css, js fixes

package.json
THis one should make main menu focus visible
=> updated main menu component to version 1.0.2 #321

package-lock.json, package.json
This will make menu items focusable (it will add visible focus)
=> Updated ds-dropdown menu component to v1.0.8 to fix issue #337

package-lock.json, package.json, src/components/site-footer/index.scss, src/css/sass/colorschemes/cannabis.scss, src/css/sass/index.scss
This will require to revisit statewide header and branding components in design system.
=> updated color values to reflect latest figma #356, Added caption styles  #260

src/rootcopy/robots.txt, src/templates/_data/sitemap.json, src/templates/manual-content/sitemap.njk
Added template to build sitemap (copied from covid)
Added url block list to exclude from sitemap as 11ty data file
Added logic to sitemap template to skip anything in the sitemap exclude data file
=> add a block list to prevent index pages and fragments from being indexed

src/components/regulatory-outline/_regulatory-outline.scss
=> #275 Add cagov- prefix to class.

package-lock.json, package.json, pages/_includes/layouts/templates/landing.njk, pages/_includes/layouts/templates/page.njk, pages/_includes/layouts/templates/post.njk, pages/_includes/layouts/templates/search.njk, pages/_includes/layouts/templates/single-column.njk, src/components/site-footer/index.scss
This fixes:
- Statewide-header/header
- remove sticky property altogether. (Revisit it later)
- decrease spacing between CA.gov icon and tagline (8px)
- Department/agency Footer
- space between logo and menu items should be 24px
- Statewide footer
- space between ca.gov icon and first link should be 24px / 16px in mobile
- Back to top
- should animate in and out of the side of the screen
- it should have white background and drop shadow
- on scroll up it should appear immediately
- Per page feedback
- It should not be full width but width of the page
- Feedback section background color should be primary
- Skip-to content
- Remove outline from main content on focus.
- Base-css (content)
- Remove grey boxes from search results
- Remove extra left padding in main content in mobile (edited)
=> Updating multiple components with multiple fixes based on headless review

.eleventy.js, package-lock.json, package.json, pages/_includes/layouts/templates/landing.njk, src/components/post-list-headless/_style.scss, src/components/post-list-headless/get-posts.js, src/components/post-list-headless/index.js, src/components/post-list-headless/render.js, src/js/index-headless.js
Same as #425, but targeting the `development` branch.
=> Development: update post-list rendering based on Drought

wordpress/config/wordpress-to-github.config.json
Reverts cagov/cannabis.ca.gov#439
=> Revert "disable redirect retrieval"

odi-publishing/wordpress-to-github.config.json
ignore timestamp part of response
=> this should stop chatty cron

package-lock.json
=> Static content update to main branch from WordPress API > AWS Lambda cagov/cannabis-lambda-sync-github > cagov/static-content-cannabis

pages/_includes/base-layout.njk, src/css/_wordpress.scss
=> Coda qafixes

pages/_content/_content.11tydata.js, pages/_includes/layouts/single-column.njk, src/css/_post.scss, src/css/index.scss
Adds category and date to all posts/announcements.
=> Fix each announcement

.eleventy.js, pages/_includes/base-layout.njk
Make the cannabis-local-ordinances data viz JS only load on the data viz page
=> Main data viz one page only

.github/workflows/eleventy_build_headless.yml, .github/workflows/eleventy_build_main.yml
Clone static cache headers into main and headless YML files (cloned from @cagov/drought.ca.gov)
=> Add static cache headers for assets, fonts and media folders

src/components/scrollable-card/src/behavior.js, src/components/scrollable-card/src/css/glider-custom.scss, src/css/_theme-components.scss, src/css/_theme-overrides.scss, src/css/_wordpress.scss
* Add CSS support for blockquotes and blockquotes in wordpress media text containers.
* Styles from WordPress and CAWeb style sheets brought in to accompany WP editor layouts.
* Update glider dimensions for scrollable card grid (so that 376px images do not scale outside their fixed, required dimensions)
* add support for wordpress pull quote CSS
=> Main 2022 12 05 pull quote

src/css/_theme-overrides.scss, src/css/_wordpress.scss
Update WordPress Gutenberg Image block css rendering behavior for static site.
=> Add WP Image rendering support

.github/workflows/eleventy_build_main.yml, .github/workflows/static_content_update_main.yml
Use cancel in progress feature of concurrency groups
=> Main cancel in progress

.github/workflows/eleventy_build_main.yml, .github/workflows/static_content_update_main.yml
=> Try different cancel in progress syntax

src/js/eleventy/event-list/get-posts.js
Make event date filter show recent events for a couple of days after the event. The current dates events were dropping off
=> Event date filtering

package-lock.json
Some issue going on today with the build pipeline. Manually updating content package.
=> bump content package manually

pages/_data/sitemap.json
The site map exclusions are not wildcards at the moment, so these additional links need to be excluded.
=> Added additional exclusions for sitemap that were missed.

README.md
* Improve readability of README file
* Update and clarify notes on the technical systems
* Update lead engineer as @jbum is taking over for @chachasikes.
=> 2023 01 30 readme edits

src/css/_figure.scss, src/css/index.scss
Removes video background here https://api.cannabis.ca.gov/?page_id=13062&preview=1&_ppp=be62ac1a46
=> Remove background color on figure element.

pages/search.njk
Sanitizing search input on search page.
=> Sanitized input on search page.

pages/_includes/breadcrumb-post.njk, pages/_includes/breadcrumb.njk, src/css/_wordpress.scss, src/css/index.scss
adds a print button at the upper right hand corner on all the pages and posts
=> adds print button on all pages

pages/_includes/breadcrumb-post.njk, pages/_includes/breadcrumb.njk, src/css/_wordpress.scss, src/css/index.scss
adds a print button at the upper right hand corner on all the pages and posts
=> adds print button on all pages and posts

.eleventy.js
@mukkhtarr reported an issue in which links were not being translated to the canonical URL as expected.  
I did some testing, and found this occurs on pages which contain media URLs.  The code that was skipping the media URLs was also skipping translation of non-media URLs, since it was operating on the HTML as a whole, rather than breaking out the hrefs individually.
Here I've modified the code to break out the hrefs individually, and apply the media-skipping logic on a per-URL basis, rather than a per-page basis.
=> Modified link transformer to examine links individually.

.eleventy.js, src/css/index.scss
Applying query loop styles and Jim's Link transformer change from main to staging
=> fixes query loop urls and formatting

pages/_includes/base-layout.njk
Added state website alert code.
Site has been tested using the preview method described here.
cagov/odi-engineering#97
=> Added state website alert for emergency messages.

pages/_includes/site-navigation.njk
Achieves a perfect 100% Lighthouse Accessibility Score
=> fixes accessibility issue of duplicate id

pages/_includes/base-layout.njk
adding facebook domain verification meta tag requested by David Szeto for SWELL/FIONA Hutton Consumer Awareness compaign
=> adds facebook domain verification meta tag

pages/_includes/statewide-footer.njk
fixes the circular link issue which was caused due to using query loops
=> fixes the circular link issue reported by devin gray

pages/_includes/base-layout.njk, pages/search.njk
Added noindex meta tag for search page, to prevent google and other crawlers from indexing it.
=> Added noindex meta tag for search page, to prevent google and other crawlers from indexing it.

.github/workflows/eleventy_build_pr.yml
Fixed bug which broke pr preview when branch names contained uppercase.
=> Fixed bug which broke pr preview when branch names contained uppercase.

.github/workflows/eleventy_build_main_mukhtar.yml
Testing the build pipeline before the transition
=> testing DCC AWS Resources

.github/workflows/eleventy_build_main.yml, .github/workflows/eleventy_build_main_old.yml, .github/workflows/eleventy_build_pr_old.yml, .github/workflows/eleventy_build_staging_old.yml
modifies AWS configuration to use DCC owned AWS account
=> aws transition prep
