- blocks/hero/block.js
- blocks/hero/plugin.php
- blocks/hero/style.css
- includes/class-cagov-design-system.php
We are Making custom gutenberg blocks which let us define editable fields for specific HTML tag content or use a WordPress integrated image upload feature.
The above image was created in this new gutenberg block editor by entering text for header, paragraph, button and uploading an image
> hero block added

- src/css/manual-caweb.v1.0.1.css
- src/manual-caweb.v1.0.1.js
Updated the CSS and JS manual files for cannabis.
This includes the CSS & JS for the PDF links, with some visual changes updated by @adam-little.
Included the external link code as a reference, but left it commented out since it is a slightly different feature, but is also similar.
Note: This code can be a reference for adding this features to the design system. Konstantin worked on this for Covid earlier in the year & we could scope this out as a new feature.
> Update manual CSS and JS

- package-lock.json
- package.json
- src/css/sass/index.scss
New versions of some CSS only modules were published that conform to file naming patterns for css files. The latest version of these packages were installed and the imports updated
> update file import to match new package file names

- package.json
- src/css/index.css
- src/templates/_includes/statewide-header.njk
This small change to ds-statewide-header markup corresponds to a design-system change at cagov/design-system#120. We should wait for upstream changes in the design-system before merging this change here in cannabis.ca.gov.
> Rename ofiicial-logo to official-logo

- .github/workflows/e2e-cypress.yml
- .github/workflows/e2e.yml
- .github/workflows/redirects.yml
Stop the end to end testing workflows from running on a schedule, they have been running smoothly, satisfied these tools are not flaky with this test suite
> Slow down workflows

- package-lock.json
- package.json
- src/js/index-headless.js
This update will hide statewide-header on scroll up and will make content navigation sticky.
> updated content-navigation to v1.0.4 and statewide-header to v1.0.8 #234

- wordpress/wordpress-to-github.config.json
Reverts cagov/cannabis.ca.gov#388
This is causing url match errors.
> Revert "adding "api." to the cannabis wordpress source URL"

- src/components/table/_table.scss
- src/css/sass/index.scss
- `.wp-block-table table, .wp-block-table table td, .wp-block-table table th {border: 1px solid var(--gray-200,#ededef)!important;` overrides the border color  but I believe it can be delted through the Wordpress uI at CAWeb Options > Custom CSS > Manual CSS
- Related PR: https://github.com/cagov/design-system/pull/144
> #387 Table styles.

- src/js/headless/index.js
On covid we run this on the homepage and equity dash. 
Do we want this event firing on all pages on cannabis @traintestbritt? It is throttled so won't have any visitor impact.
box tracker import removed because that is only used on covid for tracking when specific charts come into view on the equity dash
> add scroll tracking to all pages

- .eleventy.js
- pages/_includes/layouts/index.njk
Favicon got lost when we did the media url update, this fixes the favicon reference
Checked for other similar issues, found none
Also refactored regex with Carter's suggestion
> replace favicon, refactor media regex

- pages/_includes/layouts/index.njk
Headless template assignments were no longer working as desired: internal pages were getting the landing template assigned so they are missing the content navigation now on headless.cannabis.ca.go
This changes the template assignment logic to match values now returned from wordpress
> fix template assignments to match what is provided by latest wordpress

- wordpress/config/wordpress-to-github.config.json
The redirect endpoint is changing its updated date hourly
I cannot tell this service to retrieve the data via proxy because it uses the WordPress host as the url base
Retrieving a new redirects file every hour causes
- Write to github
- Message to slack
- New build to AWs
- CloudFront cache clear
The CloudFront cache clear looks like it will end up costing $1/day if it continues like this so I am disabling until we can remove the date from the redirects file
> disable redirect retrieval

- .github/workflows/eleventy_build_staging_pantheon.yml
Adds CloudFront cache invalidation to the GitHub Action for staging.cannabis.ca.gov builds.
> Add CloudFront invalidation to staging

- .github/workflows/eleventy_build_main.yml
Per #624, this PR alters the `main` publishing workflow in GitHub Actions.
For now, we need to push the production site to a second, new bucket in S3. This will allow us to run both headless.cannabis.ca.gov and cannabis.ca.gov concurrently, until we're ready to totally switch over. 
To summarize, this PR will push the site out to two separate S3 buckets.
I've also replaced the S3 and Cloudfront steps to match current best practices (credit goes to Jim for his work on Covid here).
> Add cannabis.ca.gov bucket to GH Action

- pages/page-not-found.njk
Adds a `/page-not-found` page to the repo.
Doing it this way allows us to cut away a lot of the content-related layout, like breadcrumbs. Also, I think it makes sense to do this as a hard-coded page due to the hard-coded S3/Cloudfront set-up.
> Add 404 page

- .eleventy.js
- pages/announcements.njk
- src/components/post-list/_paginated.scss
- src/css/index.scss
- src/js/eleventy/post-list/render.js
Fixes the announcements page.
* Minimum style changes to help the page look more like the live Flywheel version.
* Fixes to post-list rendering to help out with paginated content.
Tried to do this with the least edits possible.
> Fix announcements page

- .eleventy.js
- .github/workflows/eleventy_build_headless.yml
- .github/workflows/eleventy_build_pr.yml
- .github/workflows/eleventy_build_staging.yml
- config/config.json
- config/index.js
- package-lock.json
- package.json
- pages/_data/domain.js
* Split build YML files into two processes - one for production and one for headless. This includes two different deployment buckets (deploy_production and deploy_headless) - which are needed for syncing the correct build.
* Change DOMAIN usage, allow setting domain from cross env/env variables
* Remove DOMAIN settings from pages/_data/domain.js - we were not using it, all domain rewrites go through htmlTransforms
* Update package.json with local site building scripts (for testing domain path switching)
* Include a temporary patch on the og meta path that has a logic conflict with the html rewrite patterns (results in double slash) - need too look at this more closely later on.
Note - any absolute paths will be maintained and not automatically converted to a relative path. 
If the content …
> Main domain fixes

- config/config.json
- pages/pages.11tydata.js
The Problem:
We were getting a poppy favicon when we wanted a cannabis leaf.
Diagnosis:
page_icon (which was pointing to the cannabis icon) was not actually in use.
favicon (which was in use) was pointing to the poppy icon.
The Fix:
Fixed this so that page_icon is commented out / renamed for clarity, and favicon points to the desired icon (the cannabis leaf). 
Tested on Chrome, Firefox, Safari, iPhone.
> Corrected page icon and favicon references. 

- pages/_includes/layouts/press-release.njk
- src/css/_post.scss
Added date display to press releases.  Can be tested by using the following relative URL
`2020/05/state-cannabis-licensing-authorities-offer-60-day-license-fee-deferrals/`
BEFORE
AFTER
> Issue #186. Added date display and styling to press releases.

- .github/workflows/eleventy_build_headless.yml
There are two workflows with the name '11ty build production site' -- I am renaming one of them '11ty build production site **headless**' so I can distinguish between the two more easily in the Actions log.
> Rename a workflow to reduce ambiguity

- src/css/index.scss
Affects styling of lists on several pages (any where where ol.steps appears), which had not been using the gold-circle and line scheme that is used on the Wordpress review styling.  This adds a styling override which corrects this.
* pages/apply-for-an-equity-fee-waiver.html
* pages/banking-insurance.html
* pages/disaster-relief-programs.html
* pages/how-regulations-are-made.html
* pages/medicinal-cannabis.html
* pages/work-for-dcc.html
It looked like a generic list, needs to look like this:
> Added styling for job application steps at /about-us/work-for-dcc/ and other pages.

- pages/_data/sitemap.json
- pages/sitemap.njk
Reject all urls that contain -DRAFT or -MORGUE from showing up in the sitemap.  This makes it easier for Wes to retire old pages without outright deleting them.
Added testing-page to sitemap exclusions.
> Programmatic sitemap exclusions. 

- .github/workflows/eleventy_build_main.yml
Since media is no longer backed up on the static-repo, this copies all media to a second bucket (without deleting anything), just to have a second copy. Normally takes just a few seconds.
> Added media backup step to build.

- .github/workflows/eleventy_build_main.yml
Now that bucket versioning is enabled on the cannabis.ca.gov S3 bucket, it is no longer necessary to backup the media library to a separate S3 bucket.  Deleted and modified files will be preserved in the versioning history.  These files are also redundantly backed up on Pantheon itself.
This will save a few additional seconds of build time.
> Removed redundant backup step.

- .github/workflows/eleventy_build_staging.yml
This updates the workflow for building from staging branch to more closely match what happens in eleventy_build_main, which has been updated several times since this was written.
* Uses the concurrency system that Chach introduced for stopping prior jobs, instead of the prior method.
* Uses direct aws cli calls instead of the jakejarvis and chetan plugins.
* Does the correct things with the media (leaving links to in place and ignoring media during sync).
> Updated eleventy_build_staging to use newer ideas from eleventy_build_main

- .github/workflows/eleventy_build_main.yml
As documented here, we've had two build failures on Cannabis caused by failure of AWS Cloudfront invalidation, which sometimes appears overloaded. This is generally fixed by trying again. 
This patch increases the retries from 2 to 6, in an attempt to work around this problem. I used these two pages as reference. 
Setting retry on AWS:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html#cli-usage-retries-modes-adaptive
Setting environment variables in workflow:
https://docs.github.com/en/actions/learn-github-actions/variables
According to the AWS docs, a backoff delay is added to each successive retry, capping at 20 seconds. This should help if the cloudfront congestion is relatively short term.
> Increasing retries on Cloudfront invalidation from 2 to 6.

- src/js/analytics/google-analytics.js
This modifies the current Google Analytics IDs to the newly requisitioned Google Analytics 4 IDs.
```
gtag("config", "G-69TD0KNT0F"); // Statewide GA4 measurement ID
gtag("config", "G-75V2BNQ3DR"); // DCC (Cannabis) GA4 measurement ID
```
The code was already essentially the same as the 'Custom Template Setup' described at https://webstandards.ca.gov/add-analytics-to-your-site/, so the only changed needed was to change the IDs.
> Updated GA initialization to use GA4 IDs in accordance state policy.

- pages/_includes/statewide-footer.njk
removes circular link issue which was caused by query loops
> removes circular link issue reported by devin gray

- pages/search.njk
Search result pages contain injectable content.  Bad actors can create false search results by asking Google to search on search-result URLs.  These pages then show up in search results.
This is a short-term fix for the problem, that inhibits such pages from appearing onscreen.  It does not change the paging counts, and a longer term fix will be needed.  
Here is an example of a page where all the results have been inhibited, but the page-count still shows up.
Ideally, we need administrator access to the Google Programmatic Search Console, so we can inhibit these pages by URL on the server-side.
I will continue to modify the current method so that it has fewer artifacts.
> Prevent search pages from showing up in the results of searches. 
